### ISSUE TITLE
build fails on ubuntu 16.04 32 bit

### ISSUE THREAD

**Issue by rghvdberg** [piem/vamp-aubio-plugins#3]
seems to fail at `waf configure`
```
......
+ popd
~/git/vamp-aubio-plugins
Setting top to                           : /home/rob/git/vamp-aubio-plugins 
Setting out to                           : /home/rob/git/vamp-aubio-plugins/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Traceback (most recent call last):
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 175, in run_commands
    ctx=run_command(cmd_name)
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 166, in run_command
    ctx.execute()
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Configure.py", line 87, in execute
    super(ConfigurationContext,self).execute()
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/rob/git/vamp-aubio-plugins/.waf-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/rob/git/vamp-aubio-plugins/wscript", line 58, in configure
    local_vamp_stlib = os.path.join(local_vamp_lib, local_vamp_stlib)
UnboundLocalError: local variable 'local_vamp_lib' referenced before assignment
The project was not configured: run "waf configure" first!
```

**Comment by piem** [comment]
hello @rghvdberg 

Thanks for your report. I've just pushed a patch for it, please re-open if that doesn't help.

best, piem
