### ISSUE TITLE
Can't load Aubio in MacOS arm64

### ISSUE THREAD

**Issue by asapsmc** [piem/vamp-aubio-plugins#6]
I can't use Aubio plugins in Sonic Visualiser in MacOS M1. I understand this version wasn't prepared for arm64 processors, but just wanted to let you know. 
`/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib
Library cannot be loaded: dlopen(/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib, 0x0006): tried: '/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib' (no such file), '/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) 
/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib
Library cannot be loaded: dlopen(/Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib, 0x0006): Library not loaded: /usr/local/lib/libaubio.5.dylib Referenced from: /Users/asap/Library/Audio/Plug-Ins/Vamp/vamp-aubio.dylib Reason: tried: '/usr/local/lib/libaubio.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libaubio.5.dylib' (no such file), '/usr/local/lib/libaubio.5.dylib' (no such file), '/usr/lib/libaubio.5.dylib' (no such file, not in dyld cache) `

**Comment by juanmartin** [comment]
Hi, I also stumbled upon this, so I tried to build it from source using the provided `./build_osx.sh` script.

Build failed, copying logs from the point it started failing:
```
[114/243] Compiling tests/src/test-fmat.c
10:00:35 runner ['/usr/bin/clang', '-g', '-Wall', '-Wextra', '-O2', '-fPIC', '-Isrc', '-I../src', '-Itests', '-I../tests', '-I/opt/homebrew/Cellar/rubberband/3.3.0/include', '-I/opt/homebrew/Cellar/libsamplerate/0.2.2/include', '-I/opt/homebrew/Cellar/libvorbis/1.3.7/include', '-I/opt/homebrew/Cellar/libogg/1.3.5/include', '-I/opt/homebrew/Cellar/flac/1.4.3/include', '-DHAVE_CONFIG_H=1', '-DAUBIO_PREFIX="/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio-dist"', '-DPACKAGE="aubio"', '-DAUBIO_UNSTABLE_API=1', '-DAUBIO_TESTS_SOURCE=/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio/build/tests/44100Hz_44100f_sine441_stereo.wav', '../tests/src/test-fmat.c', '-c', '-o/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio/build/tests/src/test-fmat.c.44.o']
ld: warning: ignoring file /opt/homebrew/Cellar/libsamplerate/0.2.2/lib/libsamplerate.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/libogg/1.3.5/lib/libogg.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/libvorbis/1.3.7/lib/libvorbis.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/flac/1.4.3/lib/libFLAC.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/libvorbis/1.3.7/lib/libvorbisenc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/rubberband/3.3.0/lib/librubberband.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_FLAC__StreamEncoderStateString", referenced from:
      _aubio_sink_flac_close in sink_flac.c.1.o
      _aubio_sink_flac_do in sink_flac.c.1.o
      _aubio_sink_flac_do_multi in sink_flac.c.1.o
  "_FLAC__metadata_object_delete", referenced from:
      _aubio_sink_flac_close in sink_flac.c.1.o
  "_FLAC__metadata_object_new", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__metadata_object_vorbiscomment_append_comment", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__metadata_object_vorbiscomment_entry_from_name_value_pair", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_delete", referenced from:
      _aubio_sink_flac_close in sink_flac.c.1.o
  "_FLAC__stream_encoder_finish", referenced from:
      _aubio_sink_flac_close in sink_flac.c.1.o
  "_FLAC__stream_encoder_get_state", referenced from:
      _aubio_sink_flac_close in sink_flac.c.1.o
      _aubio_sink_flac_do in sink_flac.c.1.o
      _aubio_sink_flac_do_multi in sink_flac.c.1.o
  "_FLAC__stream_encoder_init_file", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_new", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_process_interleaved", referenced from:
      _aubio_sink_flac_do in sink_flac.c.1.o
      _aubio_sink_flac_do_multi in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_bits_per_sample", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_channels", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_compression_level", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_metadata", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_sample_rate", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_FLAC__stream_encoder_set_verify", referenced from:
      _aubio_sink_flac_open in sink_flac.c.1.o
  "_ogg_page_eos", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_ogg_stream_clear", referenced from:
      _del_aubio_sink_vorbis in sink_vorbis.c.1.o
  "_ogg_stream_flush", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_ogg_stream_init", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_ogg_stream_packetin", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_ogg_stream_pageout", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_rubberband_available", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _aubio_pitchshift_do in pitchshift_rubberband.c.1.o
      _aubio_timestretch_push in timestretch_rubberband.c.1.o
      _aubio_timestretch_get_available in timestretch_rubberband.c.1.o
      _aubio_timestretch_do in timestretch_rubberband.c.1.o
  "_rubberband_delete", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _del_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _del_aubio_timestretch in timestretch_rubberband.c.1.o
  "_rubberband_get_latency", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _aubio_pitchshift_get_latency in pitchshift_rubberband.c.1.o
      _aubio_timestretch_get_latency in timestretch_rubberband.c.1.o
  "_rubberband_new", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _new_aubio_timestretch in timestretch_rubberband.c.1.o
  "_rubberband_process", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _aubio_pitchshift_do in pitchshift_rubberband.c.1.o
      _aubio_timestretch_push in timestretch_rubberband.c.1.o
  "_rubberband_reset", referenced from:
      _aubio_timestretch_reset in timestretch_rubberband.c.1.o
  "_rubberband_retrieve", referenced from:
      _aubio_pitchshift_do in pitchshift_rubberband.c.1.o
      _aubio_timestretch_do in timestretch_rubberband.c.1.o
  "_rubberband_set_max_process_size", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
  "_rubberband_set_pitch_scale", referenced from:
      _new_aubio_pitchshift in pitchshift_rubberband.c.1.o
      _aubio_pitchshift_set_transpose in pitchshift_rubberband.c.1.o
      _aubio_pitchshift_set_pitchscale in pitchshift_rubberband.c.1.o
      _aubio_timestretch_set_pitchscale in timestretch_rubberband.c.1.o
      _aubio_timestretch_set_transpose in timestretch_rubberband.c.1.o
  "_rubberband_set_time_ratio", referenced from:
      _aubio_timestretch_set_stretch in timestretch_rubberband.c.1.o
  "_vorbis_analysis", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_vorbis_analysis_blockout", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_vorbis_analysis_buffer", referenced from:
      _aubio_sink_vorbis_do in sink_vorbis.c.1.o
      _aubio_sink_vorbis_do_multi in sink_vorbis.c.1.o
  "_vorbis_analysis_headerout", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_analysis_init", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_analysis_wrote", referenced from:
      _aubio_sink_vorbis_close in sink_vorbis.c.1.o
      _aubio_sink_vorbis_do in sink_vorbis.c.1.o
      _aubio_sink_vorbis_do_multi in sink_vorbis.c.1.o
  "_vorbis_bitrate_addblock", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_vorbis_bitrate_flushpacket", referenced from:
      _aubio_sink_vorbis_write in sink_vorbis.c.1.o
  "_vorbis_block_clear", referenced from:
      _del_aubio_sink_vorbis in sink_vorbis.c.1.o
  "_vorbis_block_init", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_comment_add_tag", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_comment_clear", referenced from:
      _del_aubio_sink_vorbis in sink_vorbis.c.1.o
  "_vorbis_comment_init", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_dsp_clear", referenced from:
      _del_aubio_sink_vorbis in sink_vorbis.c.1.o
  "_vorbis_encode_init_vbr", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
  "_vorbis_info_clear", referenced from:
      _del_aubio_sink_vorbis in sink_vorbis.c.1.o
  "_vorbis_info_init", referenced from:
      _aubio_sink_vorbis_open in sink_vorbis.c.1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio/build'
Build failed
 -> task in 'aubio' failed with exit status 1:
	{task 4540212368: cshlib cvec.c.1.o,pitchshift_dummy.c.1.o,pitchshift_rubberband.c.1.o,rubberband_utils.c.1.o,timestretch_dummy.c.1.o,timestretch_rubberband.c.1.o,fmat.c.1.o,fvec.c.1.o,audio_unit.c.1.o,ioutils.c.1.o,sink.c.1.o,sink_apple_audio.c.1.o,sink_flac.c.1.o,sink_sndfile.c.1.o,sink_vorbis.c.1.o,sink_wavwrite.c.1.o,source.c.1.o,source_apple_audio.c.1.o,source_avcodec.c.1.o,source_sndfile.c.1.o,source_wavread.c.1.o,utils_apple_audio.c.1.o,lvec.c.1.o,mathutils.c.1.o,musicutils.c.1.o,notes.c.1.o,onset.c.1.o,peakpicker.c.1.o,pitch.c.1.o,pitchfcomb.c.1.o,pitchmcomb.c.1.o,pitchschmitt.c.1.o,pitchspecacf.c.1.o,pitchyin.c.1.o,pitchyinfast.c.1.o,pitchyinfft.c.1.o,awhitening.c.1.o,dct.c.1.o,dct_accelerate.c.1.o,dct_fftw.c.1.o,dct_ipp.c.1.o,dct_ooura.c.1.o,dct_plain.c.1.o,fft.c.1.o,filterbank.c.1.o,filterbank_mel.c.1.o,mfcc.c.1.o,ooura_fft8g.c.1.o,phasevoc.c.1.o,specdesc.c.1.o,statistics.c.1.o,tss.c.1.o,sampler.c.1.o,wavetable.c.1.o,beattracking.c.1.o,tempo.c.1.o,a_weighting.c.1.o,biquad.c.1.o,c_weighting.c.1.o,filter.c.1.o,resampler.c.1.o,hist.c.1.o,log.c.1.o,parameter.c.1.o,scale.c.1.o,strutils.c.1.o,windll.c.1.o,vecutils.c.1.o -> libaubio.dylib}
['/usr/bin/clang', '-dynamiclib', '-install_name', '/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio-dist/lib/libaubio.5.dylib', '-Wl,-compatibility_version,5', '-Wl,-current_version,5.4.8', 'src/cvec.c.1.o', 'src/effects/pitchshift_dummy.c.1.o', 'src/effects/pitchshift_rubberband.c.1.o', 'src/effects/rubberband_utils.c.1.o', 'src/effects/timestretch_dummy.c.1.o', 'src/effects/timestretch_rubberband.c.1.o', 'src/fmat.c.1.o', 'src/fvec.c.1.o', 'src/io/audio_unit.c.1.o', 'src/io/ioutils.c.1.o', 'src/io/sink.c.1.o', 'src/io/sink_apple_audio.c.1.o', 'src/io/sink_flac.c.1.o', 'src/io/sink_sndfile.c.1.o', 'src/io/sink_vorbis.c.1.o', 'src/io/sink_wavwrite.c.1.o', 'src/io/source.c.1.o', 'src/io/source_apple_audio.c.1.o', 'src/io/source_avcodec.c.1.o', 'src/io/source_sndfile.c.1.o', 'src/io/source_wavread.c.1.o', 'src/io/utils_apple_audio.c.1.o', 'src/lvec.c.1.o', 'src/mathutils.c.1.o', 'src/musicutils.c.1.o', 'src/notes/notes.c.1.o', 'src/onset/onset.c.1.o', 'src/onset/peakpicker.c.1.o', 'src/pitch/pitch.c.1.o', 'src/pitch/pitchfcomb.c.1.o', 'src/pitch/pitchmcomb.c.1.o', 'src/pitch/pitchschmitt.c.1.o', 'src/pitch/pitchspecacf.c.1.o', 'src/pitch/pitchyin.c.1.o', 'src/pitch/pitchyinfast.c.1.o', 'src/pitch/pitchyinfft.c.1.o', 'src/spectral/awhitening.c.1.o', 'src/spectral/dct.c.1.o', 'src/spectral/dct_accelerate.c.1.o', 'src/spectral/dct_fftw.c.1.o', 'src/spectral/dct_ipp.c.1.o', 'src/spectral/dct_ooura.c.1.o', 'src/spectral/dct_plain.c.1.o', 'src/spectral/fft.c.1.o', 'src/spectral/filterbank.c.1.o', 'src/spectral/filterbank_mel.c.1.o', 'src/spectral/mfcc.c.1.o', 'src/spectral/ooura_fft8g.c.1.o', 'src/spectral/phasevoc.c.1.o', 'src/spectral/specdesc.c.1.o', 'src/spectral/statistics.c.1.o', 'src/spectral/tss.c.1.o', 'src/synth/sampler.c.1.o', 'src/synth/wavetable.c.1.o', 'src/tempo/beattracking.c.1.o', 'src/tempo/tempo.c.1.o', 'src/temporal/a_weighting.c.1.o', 'src/temporal/biquad.c.1.o', 'src/temporal/c_weighting.c.1.o', 'src/temporal/filter.c.1.o', 'src/temporal/resampler.c.1.o', 'src/utils/hist.c.1.o', 'src/utils/log.c.1.o', 'src/utils/parameter.c.1.o', 'src/utils/scale.c.1.o', 'src/utils/strutils.c.1.o', 'src/utils/windll.c.1.o', 'src/vecutils.c.1.o', '-o/Users/juanmartin/REPOS/vamp-aubio-plugins/contrib/aubio/build/src/libaubio.dylib', '-framework', 'CoreFoundation', '-framework', 'AudioToolbox', '-framework', 'Accelerate', '-framework', 'Accelerate', '-L/opt/homebrew/Cellar/rubberband/3.3.0/lib', '-L/opt/homebrew/Cellar/libsamplerate/0.2.2/lib', '-L/opt/homebrew/Cellar/libvorbis/1.3.7/lib', '-L/opt/homebrew/Cellar/libogg/1.3.5/lib', '-L/opt/homebrew/Cellar/flac/1.4.3/lib', '-lm', '-lrubberband', '-lsamplerate', '-lvorbisenc', '-lvorbis', '-logg', '-lFLAC']
Traceback (most recent call last):
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 171, in run_commands
    parse_options()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 144, in parse_options
    Context.create_context('options').execute()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/wscript", line 29, in options
    opt.load('compiler_cxx')
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 90, in load
    fun(self)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Tools/compiler_cxx.py", line 36, in options
    opt.load_special_tools('cxx_*.py')
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 171, in run_commands
    parse_options()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Scripting.py", line 144, in parse_options
    Context.create_context('options').execute()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/wscript", line 29, in options
    opt.load('compiler_cxx')
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 90, in load
    fun(self)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Tools/compiler_cxx.py", line 36, in options
    opt.load_special_tools('cxx_*.py')
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/Users/juanmartin/REPOS/vamp-aubio-plugins/.waf3-1.8.22-596301b77b6d6efab064109ecd67cd79/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```
